BASE_URL = 'https://qa-scooter.praktikum-services.ru/'
CREATE_COURIER = BASE_URL + '/api/v1/courier'
DELETE_COURIER = BASE_URL + '/api/v1/courier/'
LOGIN_COURIER = BASE_URL + '/api/v1/courier/login'
CREATE_ORDER = BASE_URL + '/api/v1/orders'
GET_ORDERS = BASE_URL + '/api/v1/orders'